name: automerge

on:
  pull_request:
    types: [synchronize]
  pull_request_review:
    types: [submitted]
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'Pull request number to check'
        required: true

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Automerge PR
        run: |
          REQUIRED_APPROVALS=1
          PR_NUMBER=""
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]
          then
            PR_NUMBER=${{ github.event.inputs.pr_number }}
          elif [ "${{ github.event_name }}" == "pull_request" ] || [ "${{ github.event_name }}" == "pull_request_review" ]
          then
            PR_NUMBER=${{ github.event.pull_request.number }}
          fi

          if [ "$PR_NUMBER" == "" ]
          then
            echo "PR number not found, exiting..."
            exit 0
          fi

          if [ "${{ github.event_name }}" == "pull_request_review" ] && [ "${{ github.event.review.state }}" != "APPROVED" ]
          then
            echo "Review is not approved, skipping..."
            exit 0
          fi

          APPROVALS=$(gh pr view "https://github.com/${{ github.repository }}/pull/$PR_NUMBER" --json reviews | jq '[.reviews[] | select(.state=="APPROVED")] | length')
          echo "Number of approvals: $APPROVALS"
          if [ "$APPROVALS" -ge "$REQUIRED_APPROVALS" ]; then
            MERGE_RESULT=$(gh pr merge "https://github.com/${{ github.repository }}/pull/$PR_NUMBER" --merge --auto)
            echo "Merge result: $MERGE_RESULT"
          else
            echo "Not enough approvals, skipping..."
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
